version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - cache
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: 2fa-api
      DB_PASSWORD: 2fa_local_db
      DB_NAME: 2fa-api
  postgres:
    image: postgres:13.11-alpine3.18
    environment:
      POSTGRES_USER: 2fa-api
      POSTGRES_PASSWORD: 2fa_local_db
      POSTGRES_DB: 2fa-api
    ports:
      - "5432:5432"
  cache:
    image: redis:6
    ports:
      - "6379:6379"
